"""Synthetic Neuropixels data generation for W2T-BKIN.

Creates synthetic SpikeGLX metadata files and Kilosort spike sorting outputs
for testing and demos.

Features:
- `EcephysSynthParams` dataclass for generation parameters
- SpikeGLX .meta file generation with realistic parameters
- Kilosort output generation (spike_times, cluster_info, templates)
- Configurable probe geometry and unit properties
- Deterministic generation based on seed

Example:
    from synthetic.ecephys_synth import EcephysSynthParams, create_spikeglx_meta, create_kilosort_output

    params = EcephysSynthParams(
        probe_type="neuropixels2.0",
        n_channels=384,
        sampling_rate=30000.0,
        n_units=20,
        recording_duration_s=60.0,
        seed=42
    )
    meta_path = create_spikeglx_meta(Path("output/probe.ap.meta"), params)
    ks_paths = create_kilosort_output(Path("output/kilosort"), params)

CLI:
    python -m synthetic.ecephys_synth --out output/ecephys --n_units 50
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Union

import numpy as np
import pandas as pd


@dataclass
class EcephysSynthParams:
    """Parameters for synthetic ecephys data generation.

    Attributes:
        probe_type: Type of Neuropixels probe ("neuropixels1.0" or "neuropixels2.0")
        n_channels: Number of recording channels (default: 384 for NP2.0)
        sampling_rate: Sampling rate in Hz (default: 30000.0)
        n_units: Number of sorted units to generate
        recording_duration_s: Duration of recording in seconds
        firing_rate_mean: Mean firing rate across units (Hz)
        firing_rate_std: Standard deviation of firing rates (Hz)
        good_unit_fraction: Fraction of units labeled as "good"
        noise_unit_fraction: Fraction of units labeled as "noise"
        seed: Random seed for reproducibility
        probe_id: Probe identifier (e.g., "imec0")
    """

    probe_type: str = "neuropixels2.0"
    n_channels: int = 384
    sampling_rate: float = 30000.0
    n_units: int = 20
    recording_duration_s: float = 60.0
    firing_rate_mean: float = 5.0
    firing_rate_std: float = 3.0
    good_unit_fraction: float = 0.70
    noise_unit_fraction: float = 0.15
    seed: int = 42
    probe_id: str = "imec0"


def create_spikeglx_meta(output_path: Union[str, Path], params: EcephysSynthParams) -> Path:
    """Create a synthetic SpikeGLX .meta file.

    Generates a minimal but valid .meta file with probe geometry and recording parameters.

    Args:
        output_path: Where to save the .meta file
        params: Generation parameters

    Returns:
        Path to created .meta file
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Determine probe type code
    probe_type_code = "21" if params.probe_type == "neuropixels2.0" else "0"

    # Generate electrode geometry (x, y) coordinates
    # Neuropixels 2.0: 2-column layout with 15 μm horizontal spacing, 15 μm vertical spacing
    geometry = []
    if params.probe_type == "neuropixels2.0":
        for i in range(params.n_channels):
            x = (i % 2) * 32  # Alternating columns at 0 and 32 μm
            y = (i // 2) * 15  # Vertical spacing 15 μm
            geometry.append(f"({x},{y})")
    else:
        # Neuropixels 1.0: 4-column staggered layout
        for i in range(params.n_channels):
            x = (i % 4) * 16  # 4 columns
            y = (i // 4) * 20  # Vertical spacing 20 μm
            geometry.append(f"({x},{y})")

    geometry_str = "".join(geometry)

    # Calculate file size (approximate)
    bytes_per_sample = params.n_channels * 2  # 16-bit integers
    total_samples = int(params.sampling_rate * params.recording_duration_s)
    file_size = bytes_per_sample * total_samples

    # Write .meta file
    meta_content = f"""# SpikeGLX Meta File - Synthetic Neuropixels Data
# Generated by w2t-bkin synthetic module

imSampRate={params.sampling_rate}
nSavedChans={params.n_channels}
imDatPrb_type={probe_type_code}
fileSizeBytes={file_size}
~imBandpass=300 10000
~snsGeomMap={geometry_str}
"""

    output_path.write_text(meta_content, encoding="utf-8")
    return output_path


def create_kilosort_output(output_dir: Union[str, Path], params: EcephysSynthParams) -> Dict[str, Path]:
    """Create synthetic Kilosort spike sorting output files.

    Generates:
    - spike_times.npy: Spike timestamps in samples
    - spike_clusters.npy: Cluster ID for each spike
    - cluster_info.tsv: Unit quality metrics and labels
    - templates.npy: Average waveforms for each unit
    - cluster_KSLabel.tsv: Kilosort quality labels (fallback format)

    Args:
        output_dir: Directory to save Kilosort files
        params: Generation parameters

    Returns:
        Dictionary mapping file type to Path
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    rng = np.random.RandomState(params.seed)

    # Calculate number of units by quality
    n_good = int(params.n_units * params.good_unit_fraction)
    n_noise = int(params.n_units * params.noise_unit_fraction)
    n_mua = params.n_units - n_good - n_noise

    # Generate spike times and cluster assignments
    all_spike_times = []
    all_spike_clusters = []
    total_samples = int(params.sampling_rate * params.recording_duration_s)

    for cluster_id in range(params.n_units):
        # Generate firing rate for this unit
        firing_rate = max(0.1, rng.normal(params.firing_rate_mean, params.firing_rate_std))

        # Generate spike times as Poisson process
        n_spikes = int(firing_rate * params.recording_duration_s)
        spike_times = rng.uniform(0, total_samples, n_spikes).astype(np.int64)
        spike_times.sort()

        all_spike_times.append(spike_times)
        all_spike_clusters.append(np.full(n_spikes, cluster_id, dtype=np.int32))

    # Concatenate and sort by time
    spike_times = np.concatenate(all_spike_times)
    spike_clusters = np.concatenate(all_spike_clusters)
    sort_idx = np.argsort(spike_times)
    spike_times = spike_times[sort_idx]
    spike_clusters = spike_clusters[sort_idx]

    # Save spike_times.npy and spike_clusters.npy
    spike_times_path = output_dir / "spike_times.npy"
    spike_clusters_path = output_dir / "spike_clusters.npy"
    np.save(spike_times_path, spike_times)
    np.save(spike_clusters_path, spike_clusters)

    # Generate cluster_info.tsv with quality metrics
    cluster_info = []
    for cluster_id in range(params.n_units):
        # Assign quality label
        if cluster_id < n_good:
            label = "good"
            contamination = rng.uniform(0.0, 0.05)  # Low contamination
            amplitude = rng.uniform(80.0, 200.0)  # High amplitude
        elif cluster_id < n_good + n_noise:
            label = "noise"
            contamination = rng.uniform(0.3, 0.9)  # High contamination
            amplitude = rng.uniform(10.0, 40.0)  # Low amplitude
        else:
            label = "mua"
            contamination = rng.uniform(0.1, 0.3)  # Medium contamination
            amplitude = rng.uniform(40.0, 80.0)  # Medium amplitude

        cluster_info.append(
            {
                "cluster_id": cluster_id,
                "KSLabel": label,
                "ContamPct": contamination,
                "amp": amplitude,
                "n_spikes": len(all_spike_times[cluster_id]),
                "firing_rate": len(all_spike_times[cluster_id]) / params.recording_duration_s,
                "sh": rng.uniform(0, params.n_channels - 1),  # Peak channel
            }
        )

    cluster_info_df = pd.DataFrame(cluster_info)
    cluster_info_path = output_dir / "cluster_info.tsv"
    cluster_info_df.to_csv(cluster_info_path, sep="\t", index=False)

    # Generate templates.npy (average waveforms)
    # Shape: (n_units, n_samples_per_waveform, n_channels)
    n_samples_per_waveform = 82  # Standard Kilosort waveform length
    templates = rng.randn(params.n_units, n_samples_per_waveform, params.n_channels).astype(np.float32)

    # Make templates sparse (most channels have near-zero values)
    for i in range(params.n_units):
        peak_channel = int(cluster_info_df.loc[i, "sh"])
        mask = np.ones(params.n_channels, dtype=bool)
        # Keep only channels near peak
        nearby = np.abs(np.arange(params.n_channels) - peak_channel) <= 10
        mask[~nearby] = False
        templates[i, :, ~mask] *= 0.01  # Reduce amplitude on distant channels

    templates_path = output_dir / "templates.npy"
    np.save(templates_path, templates)

    # Generate cluster_KSLabel.tsv (fallback format)
    ks_label_df = cluster_info_df[["cluster_id", "KSLabel"]].copy()
    ks_label_path = output_dir / "cluster_KSLabel.tsv"
    ks_label_df.to_csv(ks_label_path, sep="\t", index=False)

    return {
        "spike_times": spike_times_path,
        "spike_clusters": spike_clusters_path,
        "cluster_info": cluster_info_path,
        "templates": templates_path,
        "cluster_KSLabel": ks_label_path,
    }


def build_ecephys_output(
    output_dir: Union[str, Path],
    *,
    probe_type: str = "neuropixels2.0",
    probe_id: str = "imec0",
    n_channels: int = 384,
    sampling_rate: float = 30000.0,
    n_units: int = 20,
    recording_duration_s: float = 60.0,
    seed: int = 42,
) -> Dict[str, Path]:
    """Build complete synthetic ecephys output with SpikeGLX and Kilosort data.

    Creates directory structure:
        <output_dir>/
        ├── spikeglx/
        │   └── probe.ap.meta
        └── kilosort/
            ├── spike_times.npy
            ├── spike_clusters.npy
            ├── cluster_info.tsv
            ├── templates.npy
            └── cluster_KSLabel.tsv

    Args:
        output_dir: Base output directory
        probe_type: Type of Neuropixels probe
        probe_id: Probe identifier
        n_channels: Number of recording channels
        sampling_rate: Sampling rate in Hz
        n_units: Number of sorted units
        recording_duration_s: Recording duration in seconds
        seed: Random seed

    Returns:
        Dictionary with paths to generated files
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    params = EcephysSynthParams(
        probe_type=probe_type,
        n_channels=n_channels,
        sampling_rate=sampling_rate,
        n_units=n_units,
        recording_duration_s=recording_duration_s,
        seed=seed,
        probe_id=probe_id,
    )

    # Create SpikeGLX directory and metadata
    spikeglx_dir = output_dir / "spikeglx"
    spikeglx_dir.mkdir(exist_ok=True)
    meta_path = create_spikeglx_meta(spikeglx_dir / f"{probe_id}.ap.meta", params)

    # Create Kilosort directory and outputs
    kilosort_dir = output_dir / "kilosort"
    ks_paths = create_kilosort_output(kilosort_dir, params)

    return {
        "meta": meta_path,
        **{f"kilosort_{k}": v for k, v in ks_paths.items()},
    }


if __name__ == "__main__":
    """CLI for generating synthetic ecephys data."""
    import argparse

    parser = argparse.ArgumentParser(description="Generate synthetic Neuropixels data")
    parser.add_argument("--out", type=Path, default=Path("output/ecephys_synthetic"), help="Output directory")
    parser.add_argument("--probe-type", type=str, default="neuropixels2.0", choices=["neuropixels1.0", "neuropixels2.0"], help="Probe type")
    parser.add_argument("--probe-id", type=str, default="imec0", help="Probe identifier")
    parser.add_argument("--n-channels", type=int, default=384, help="Number of channels")
    parser.add_argument("--sampling-rate", type=float, default=30000.0, help="Sampling rate (Hz)")
    parser.add_argument("--n-units", type=int, default=20, help="Number of units")
    parser.add_argument("--duration", type=float, default=60.0, help="Recording duration (seconds)")
    parser.add_argument("--seed", type=int, default=42, help="Random seed")

    args = parser.parse_args()

    paths = build_ecephys_output(
        args.out,
        probe_type=args.probe_type,
        probe_id=args.probe_id,
        n_channels=args.n_channels,
        sampling_rate=args.sampling_rate,
        n_units=args.n_units,
        recording_duration_s=args.duration,
        seed=args.seed,
    )

    print(f"\n✓ Generated synthetic ecephys data in: {args.out}")
    print(f"\nFiles created:")
    for name, path in paths.items():
        print(f"  - {name}: {path}")
